### ISSUE TITLE
Endotart tool is hard to see X is not being endorsed by Y.

### ISSUE THREAD

**Issue by jmikk** [Kractero/hare#2]
86/88 [psychiatrisicm](https://kractero.github.io/hare/tools/%7B%22https://nationstates.net/nation=psychiatrisicm%22%7D) is not being endorsed by 9006.

85/88 [ross_and_skye](https://kractero.github.io/hare/tools/%7B%22https://nationstates.net/nation=ross_and_skye%22%7D) is already endorsed by 9006. 

Is an example line but it blends in with all of the others, maybe is should be a different color? or list all nations that are not being endorsed at the very end?

**Comment by Kractero** [comment]
Added green and red to indicate not being endorsed vs endorsed/at limit
